using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MarimoMovement : MonoBehaviour
{

    float time;
    // Start is called before the first frame update
    void Start()
    {

    }

    void Update()
    {

        if (time < 1f)
        {
            this.transform.position = new Vector3(0, 9 - 120 * time, 0);
        }

        else if (time < 1.5f)
        {
            this.transform.position = new Vector3(0, -3 + (80) * (time - 1f), 0);
        }

        else if (time < 2.0f)
        {
            this.transform.position = new Vector3(0, 1 - (40) * (time - 1.5f), 0);
        }

        else if (time < 2.5f)
        {
            this.transform.position = new Vector3(0, -1 + (20) * (time - 2.0f), 0);
        }

        time += Time.deltaTime;


    }
    

}
